Require build-status for 8.x branch (#1752)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -5,7 +5,7 @@ on:
     branches:
       - 8.x
   pull_request:
-      branches:
+    branches:
       - 8.x
   workflow_dispatch:
 
@@ -33,8 +33,24 @@ jobs:
       - uses: gradle/actions/setup-gradle@v4
       - run: ./gradlew build --info "-PtestGradleVersion=${{ matrix.gradle }}"
 
+  # Status check that is required in branch protection rules.
+  build-status:
+    needs:
+      - build
+    runs-on: ubuntu-24.04-arm
+    if: always()
+    steps:
+      - name: Check
+        run: |
+          results=$(tr -d '\n' <<< '${{ toJSON(needs.*.result) }}')
+          if ! grep -q -v -E '(failure|cancelled)' <<< "$results"; then
+            echo "One or more required jobs failed"
+            exit 1
+          fi
+          echo "All required jobs completed successfully."
+
   publish-snapshot:
-    needs: build
+    needs: build-status
     runs-on: ubuntu-latest
     if: github.repository == 'GradleUp/shadow' && github.ref == 'refs/heads/main'
     steps:
